# Generated by Django 5.1.4 on 2024-12-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss', models.IntegerField()),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('num_telephone', models.CharField(max_length=20)),
                ('qr_url', models.CharField(max_length=255)),
                ('antecedents', models.TextField()),
            ],
            options={
                'db_table': 'dpis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'medecins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mutuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('num_adherent', models.CharField(max_length=50)),
                ('type_couverture', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mutuelles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonneContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('numero_telephone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'personnes_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('fonction', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'personnel',
                'managed': False,
            },
        ),
    ]
