# Generated by Django 5.1.4 on 2025-01-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpi',
            name='patient',
        ),
        migrations.DeleteModel(
            name='ContactPerson',
        ),
        migrations.DeleteModel(
            name='DPI',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
