# Generated by Django 5.1.4 on 2024-12-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infirmiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'infirmiers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laborantins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'laborantins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medecins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'medecins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('fonction', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'personnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radiologues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'radiologues',
                'managed': False,
            },
        ),
    ]
