# Generated by Django 5.1.4 on 2024-12-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dpis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nss', models.CharField(blank=True, max_length=255, null=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('num_telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_url', models.CharField(blank=True, max_length=255, null=True)),
                ('antecedents', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dpis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonnesContact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'personnes_contact',
                'managed': False,
            },
        ),
    ]
