# Generated by Django 5.1.4 on 2024-12-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps_bilan', models.TextField()),
            ],
            options={
                'db_table': 'bilans_biologiques',
            },
        ),
        migrations.CreateModel(
            name='BilanRadiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps_bilan', models.TextField()),
            ],
            options={
                'db_table': 'bilans_radiologiques',
            },
        ),
        migrations.CreateModel(
            name='Dpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss', models.CharField(max_length=255, null=True, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dpis',
            },
        ),
        migrations.CreateModel(
            name='ResumeConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedents', models.TextField(blank=True, null=True)),
                ('corps_resume', models.TextField(blank=True, null=True)),
                ('date_consultation', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation_crud.dpi')),
            ],
            options={
                'db_table': 'resumes_consultations',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.CharField(blank=True, max_length=255, null=True)),
                ('date_consultation', models.DateField()),
                ('bilans_biologiques', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation_crud.bilanbiologique')),
                ('bilans_radiologiques', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultation_crud.bilanradiologique')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation_crud.dpi')),
                ('resume_consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation_crud.resumeconsultation')),
            ],
            options={
                'db_table': 'consultations',
            },
        ),
    ]
