# Generated by Django 5.1.4 on 2024-12-23 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(db_column='dpis_id', on_delete=django.db.models.deletion.CASCADE, to='consultation_crud.dpi'),
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_ordonnance', models.CharField(choices=[('Validee', 'Validée'), ('Refusee', 'Refusée')], default='Refusee', max_length=8)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(db_column='consultations_id', on_delete=django.db.models.deletion.CASCADE, to='consultation_crud.consultation')),
            ],
            options={
                'db_table': 'ordonnances',
            },
        ),
    ]
