# Generated by Django 5.1.4 on 2024-12-23 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0002_alter_consultation_patient_ordonnance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='date_creation',
        ),
    ]
