# Generated by Django 5.1.4 on 2024-12-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0003_remove_ordonnance_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=255)),
                ('duree', models.IntegerField()),
                ('ordonnance', models.ForeignKey(db_column='ordonnances_id', on_delete=django.db.models.deletion.CASCADE, to='consultation_crud.ordonnance')),
            ],
            options={
                'db_table': 'medicaments',
            },
        ),
    ]
