# Generated by Django 5.1.4 on 2024-12-24 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0004_medicament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='dose',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='ordonnance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='consultation_crud.ordonnance'),
        ),
        migrations.AlterModelTable(
            name='medicament',
            table=None,
        ),
    ]
