# Generated by Django 5.1.4 on 2024-12-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0005_alter_medicament_dose_alter_medicament_ordonnance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='dose',
            field=models.CharField(max_length=255),
        ),
    ]
