# Generated by Django 5.1.4 on 2024-12-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0007_alter_medicament_ordonnance_alter_medicament_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='ordonnance',
            field=models.ForeignKey(db_column='ordonnances_id', on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='consultation_crud.ordonnance'),
        ),
    ]
