# Generated by Django 5.1.4 on 2024-12-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0008_alter_medicament_ordonnance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dpi',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpi',
            name='num_telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
