# Generated by Django 5.1.4 on 2024-12-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0013_dpi_antecedents_dpi_mutuelles_id_dpi_qr_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpi',
            name='antecedents',
        ),
    ]
