# Generated by Django 5.1.4 on 2024-12-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0014_remove_dpi_antecedents'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi',
            name='antecedents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
