# Generated by Django 5.1.4 on 2024-12-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0015_dpi_antecedents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpi',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dpi',
            name='antecedents',
        ),
        migrations.RemoveField(
            model_name='dpi',
            name='mutuelles_id',
        ),
        migrations.RemoveField(
            model_name='dpi',
            name='qr_url',
        ),
        migrations.DeleteModel(
            name='Medecin',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
