# Generated by Django 5.1.4 on 2024-12-26 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0016_remove_dpi_medecin_remove_personnel_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('fonction', models.CharField(choices=[('Medecin', 'Médecin'), ('Laborantin', 'Laborantin'), ('Radiologue', 'Radiologue')], max_length=10)),
            ],
            options={
                'db_table': 'personnel',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('nss', models.CharField(max_length=255)),
                ('mdp', models.CharField(max_length=255)),
                ('type_personnel', models.CharField(choices=[('Patient', 'Patient'), ('Personnel', 'Personnel')], max_length=10)),
                ('cree_le', models.DateField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='dpi',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation_crud.medecin'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='personnel',
            field=models.ForeignKey(db_column='personnel_id', on_delete=django.db.models.deletion.CASCADE, to='consultation_crud.personnel'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='consultation_crud.user'),
        ),
    ]
