# Generated by Django 5.1.4 on 2024-12-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0017_medecin_personnel_user_dpi_medecin_medecin_personnel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='medecin',
            field=models.ForeignKey(blank=True, db_column='medecins_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation_crud.medecin'),
        ),
    ]
