# Generated by Django 5.1.4 on 2024-12-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0018_alter_dpi_medecin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='diagnostic',
        ),
    ]
