# Generated by Django 5.1.4 on 2024-12-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0020_alter_consultation_id_alter_medecin_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpi',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='user',
        ),
        migrations.AddField(
            model_name='consultation',
            name='diagnostic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Medecin',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
