# Generated by Django 5.1.4 on 2024-12-26 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0022_medecin_personnel_user_dpi_medecin_medecin_personnel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='bilans_biologiques',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='bilans_radiologiques',
        ),
        migrations.RenameField(
            model_name='resumeconsultation',
            old_name='date_consultation',
            new_name='date_prochaine_consultation',
        ),
        migrations.RenameField(
            model_name='resumeconsultation',
            old_name='corps_resume',
            new_name='diagnostic',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='diagnostic',
        ),
        migrations.AddField(
            model_name='resumeconsultation',
            name='info_supp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeconsultation',
            name='mesure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeconsultation',
            name='symptomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='resume_consultation',
            field=models.ForeignKey(blank=True, db_column='resume_consultation_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation_crud.resumeconsultation'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='etat_ordonnance',
            field=models.CharField(choices=[('Validee', 'Validée'), ('En cours de validation', 'En cours de validation'), ('Refusee', 'Refusée')], default='Refusee', max_length=30),
        ),
        migrations.AlterField(
            model_name='resumeconsultation',
            name='patient',
            field=models.ForeignKey(db_column='dpis_id', on_delete=django.db.models.deletion.CASCADE, to='consultation_crud.dpi'),
        ),
        migrations.DeleteModel(
            name='BilanBiologique',
        ),
        migrations.DeleteModel(
            name='BilanRadiologique',
        ),
    ]
