# Generated by Django 5.1.4 on 2024-12-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0024_remove_medicament_nom_medicament_nom_medicament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='etat_ordonnance',
            field=models.CharField(choices=[('Validee', 'Validée'), ('En cours de validation', 'En cours de validation'), ('Refusee', 'Refusée')], default='Refusee', max_length=255),
        ),
    ]
