# Generated by Django 5.1.4 on 2024-12-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0025_alter_ordonnance_etat_ordonnance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'infirmiers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoinsInfirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soin', models.DateField()),
                ('description_soin', models.TextField()),
            ],
            options={
                'db_table': 'soins_infirmier',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dpi',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medecin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medicament',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ordonnance',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='personnel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='resumeconsultation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
