# Generated by Django 5.1.4 on 2025-01-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation_crud', '0026_infirmier_soinsinfirmier_alter_consultation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpi',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='dpi',
            name='user',
        ),
        migrations.DeleteModel(
            name='Infirmier',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dpi',
        ),
        migrations.DeleteModel(
            name='Medecin',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
