# Generated by Django 5.1.4 on 2024-12-26 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysesBiologiques',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_analyse', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.CharField(blank=True, max_length=255, null=True)),
                ('unite', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'analyses_biologiques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BilansBiologiques',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('synthese_bilan_bio', models.TextField(blank=True, null=True)),
                ('date_bilan', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bilans_biologiques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dpis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nss', models.CharField(blank=True, max_length=255, null=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('num_telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_url', models.CharField(blank=True, max_length=255, null=True)),
                ('antecedents', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dpis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GraphiquesTendances',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_graphique', models.DateField(blank=True, null=True)),
                ('url_graphique', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'graphiques_tendances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laborantins',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'laborantins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medecins',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('specialite', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'medecins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('fonction', models.CharField(blank=True, max_length=23, null=True)),
            ],
            options={
                'db_table': 'personnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonnesContact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'personnes_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResumesConsultations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('symptomes', models.TextField(blank=True, null=True)),
                ('mesure', models.TextField(blank=True, null=True)),
                ('antecedents', models.TextField(blank=True, null=True)),
                ('info_supp', models.TextField(blank=True, null=True)),
                ('date_prochaine_consultation', models.DateField(blank=True, null=True)),
                ('dpis_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_consultation', models.DateField(blank=True, null=True)),
                ('dpis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bilanbiologique.dpis')),
                ('resume_consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bilanbiologique.resumesconsultations')),
            ],
        ),
    ]
