# Generated by Django 5.1.4 on 2025-01-10 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilanbiologique', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultations',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='resumesconsultations',
            options={'managed': False},
        ),
    ]
