# Generated by Django 5.1.4 on 2025-01-10 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilanbiologique', '0002_alter_consultations_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultations',
            table='consultations',
        ),
        migrations.AlterModelTable(
            name='resumesconsultations',
            table='resumes_consultations',
        ),
    ]
