# Generated by Django 5.1.4 on 2024-12-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BilansRadiologiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synthese_bilan_radio', models.TextField(blank=True, null=True)),
                ('date_radiologie', models.DateField(blank=True, null=True)),
                ('type_radiologie', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bilans_radiologiques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consultations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nss', models.BigIntegerField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('num_telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_url', models.CharField(blank=True, max_length=255, null=True)),
                ('antecedents', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dpis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medecins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'medecins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('fonction', models.CharField(blank=True, max_length=23, null=True)),
            ],
            options={
                'db_table': 'personnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonnesContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'personnes_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radiologues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'radiologues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResumesConsultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('symptomes', models.TextField(blank=True, null=True)),
                ('mesure', models.TextField(blank=True, null=True)),
                ('antecedents', models.TextField(blank=True, null=True)),
                ('info_supp', models.TextField(blank=True, null=True)),
                ('date_prochaine_consultation', models.DateField(blank=True, null=True)),
                ('dpis_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resumes_consultations',
                'managed': False,
            },
        ),
    ]
