# Generated by Django 5.1.4 on 2024-12-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilanradiologique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infirmiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'infirmiers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laborantins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'laborantins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mutuelles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_mutuelle', models.CharField(blank=True, max_length=255, null=True)),
                ('type_couverture', models.CharField(blank=True, max_length=9, null=True)),
                ('num_adherent', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mutuelles',
                'managed': False,
            },
        ),
    ]
